name: 'ahrq_quality_indicators'
version: '1.0.0'
config-version: 2
require-dbt-version: ">=1.10.5,<3.0.0"

profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  tuva_last_run: '{{ run_started_at.astimezone(modules.pytz.timezone("UTC")) }}'

seeds:
  ahrq_quality_indicators:
    value_sets:
      ahrq_quality_indicators:
        pqi__measures:
          +post-hook: "{{ the_tuva_project.load_package_seed('ahrq-quality-indicators', ahrq_quality_indicators.get_ahrq_quality_indicators_package_version(), 'pqi__measures.csv.gz') }}"
        pqi__value_sets:
          +post-hook: "{{ the_tuva_project.load_package_seed('ahrq-quality-indicators', ahrq_quality_indicators.get_ahrq_quality_indicators_package_version(), 'pqi__value_sets.csv.gz') }}"
